// This file is auto-generated by faktorio-api/scripts/update-fe-migrations.ts
// Do not edit this file manually, as your changes will be overwritten.
// To regenerate this file, run 'pnpm --filter faktorio-api local-migrations-generate'.

import migration0000_dry_rick_jones from 'faktorio-db/drizzle/0000_dry_rick_jones.sql?raw'
import migration0001_glossy_siren from 'faktorio-db/drizzle/0001_glossy_siren.sql?raw'
import migration0002_groovy_cammi from 'faktorio-db/drizzle/0002_groovy_cammi.sql?raw'
import migration0003_glorious_hiroim from 'faktorio-db/drizzle/0003_glorious_hiroim.sql?raw'
import migration0004_tense_network from 'faktorio-db/drizzle/0004_tense_network.sql?raw'
import migration0005_funny_abomination from 'faktorio-db/drizzle/0005_funny_abomination.sql?raw'
import migration0006_fuzzy_epoch from 'faktorio-db/drizzle/0006_fuzzy_epoch.sql?raw'
import migration0007_past_prism from 'faktorio-db/drizzle/0007_past_prism.sql?raw'
import migration0008_noisy_mercury from 'faktorio-db/drizzle/0008_noisy_mercury.sql?raw'
import migration0009_known_gauntlet from 'faktorio-db/drizzle/0009_known_gauntlet.sql?raw'
import migration0010_clever_bloodscream from 'faktorio-db/drizzle/0010_clever_bloodscream.sql?raw'
import migration0011_tranquil_terrax from 'faktorio-db/drizzle/0011_tranquil_terrax.sql?raw'
import migration0012_nebulous_earthquake from 'faktorio-db/drizzle/0012_nebulous_earthquake.sql?raw'
import migration0013_dark_silver_samurai from 'faktorio-db/drizzle/0013_dark_silver_samurai.sql?raw'

export const localDBMigrations: Record<string, string> = {
  migration0000_dry_rick_jones,
  migration0001_glossy_siren,
  migration0002_groovy_cammi,
  migration0003_glorious_hiroim,
  migration0004_tense_network,
  migration0005_funny_abomination,
  migration0006_fuzzy_epoch,
  migration0007_past_prism,
  migration0008_noisy_mercury,
  migration0009_known_gauntlet,
  migration0010_clever_bloodscream,
  migration0011_tranquil_terrax,
  migration0012_nebulous_earthquake,
  migration0013_dark_silver_samurai
}
