CREATE TABLE `contact` (
	`id` text PRIMARY KEY NOT NULL,
	`user_id` text NOT NULL,
	`name` text,
	`street` text,
	`street2` text,
	`city` text,
	`zip` text,
	`country` text,
	`registration_no` text,
	`main_email` text,
	`vat_no` text,
	`phone_number` text,
	`created_at` text DEFAULT CURRENT_TIMESTAMP NOT NULL,
	`updated_at` text
);
--> statement-breakpoint
CREATE TABLE `invoice_item` (
	`id` integer PRIMARY KEY NOT NULL,
	`order` integer,
	`invoice_id` text NOT NULL,
	`description` text,
	`quantity` real,
	`unit_price` real,
	`unit` text,
	`vat_rate` real,
	`created_at` text DEFAULT CURRENT_TIMESTAMP NOT NULL,
	`updated_at` text,
	FOREIGN KEY (`invoice_id`) REFERENCES `invoice`(`id`) ON UPDATE no action ON DELETE cascade
);
--> statement-breakpoint
CREATE TABLE `invoice` (
	`id` text PRIMARY KEY NOT NULL,
	`user_id` text NOT NULL,
	`proforma` integer,
	`partial_proforma` integer,
	`number` text NOT NULL,
	`variable_symbol` text,
	`your_name` text,
	`your_street` text,
	`your_street2` text,
	`your_city` text,
	`your_zip` text,
	`your_country` text,
	`your_registration_no` text,
	`your_vat_no` text,
	`client_name` text,
	`client_street` text,
	`client_street2` text,
	`client_city` text,
	`client_zip` text,
	`client_country` text,
	`client_registration_no` text,
	`client_vat_no` text,
	`subject_id` integer,
	`generator_id` integer,
	`related_id` integer,
	`token` text,
	`status` text,
	`order_number` text,
	`issued_on` text,
	`taxable_fulfillment_due` text,
	`due_in_days` integer NOT NULL,
	`due_on` text NOT NULL,
	`sent_at` text,
	`paid_on` text,
	`reminder_sent_at` text,
	`cancelled_at` text,
	`bank_account` text,
	`iban` text,
	`swift_bic` text,
	`payment_method` text,
	`currency` text NOT NULL,
	`exchange_rate` real,
	`language` text,
	`transferred_tax_liability` integer,
	`supply_code` text,
	`subtotal` real,
	`total` real NOT NULL,
	`native_subtotal` real NOT NULL,
	`native_total` real,
	`remaining_amount` real,
	`remaining_native_amount` real,
	`paid_amount` real DEFAULT 0 NOT NULL,
	`note` text,
	`footer_note` text,
	`tags` text,
	`vat_base_21` real,
	`vat_21` real,
	`vat_base_15` real,
	`vat_15` real,
	`vat_base_12` real,
	`vat_12` real,
	`vat_base_10` real,
	`vat_10` real,
	`vat_base_0` real,
	`private_note` text,
	`correction` integer,
	`correction_id` integer,
	`client_email` text,
	`client_phone` text,
	`custom_id` text,
	`oss` integer,
	`tax_document` integer,
	`payment_method_human` text,
	`created_at` text DEFAULT CURRENT_TIMESTAMP NOT NULL,
	`updated_at` text,
	`published_at` text,
	`client_contact_id` text,
	FOREIGN KEY (`client_contact_id`) REFERENCES `contact`(`id`) ON UPDATE no action ON DELETE no action
);
--> statement-breakpoint
CREATE TABLE `user_invoicing_detail` (
	`user_id` text PRIMARY KEY NOT NULL,
	`name` text,
	`street` text,
	`street2` text,
	`city` text,
	`zip` text,
	`country` text,
	`main_email` text,
	`bank_account` text,
	`iban` text,
	`swift_bic` text,
	`vat_no` text,
	`registration_no` text,
	`created_at` text DEFAULT CURRENT_TIMESTAMP NOT NULL,
	`updated_at` text,
	`phone_number` text,
	`web_url` text
);
--> statement-breakpoint
CREATE INDEX `contact_user_idx` ON `contact` (`user_id`);--> statement-breakpoint
CREATE INDEX `invoice_idx` ON `invoice_item` (`invoice_id`);--> statement-breakpoint
CREATE UNIQUE INDEX `invoice_item_invoice_id_order_unique` ON `invoice_item` (`invoice_id`,`order`);--> statement-breakpoint
CREATE INDEX `invoices_user_idx` ON `invoice` (`user_id`);--> statement-breakpoint
CREATE UNIQUE INDEX `invoice_user_id_number_unique` ON `invoice` (`user_id`,`number`);--> statement-breakpoint
CREATE UNIQUE INDEX `user_invoicing_detail_user_id_unique` ON `user_invoicing_detail` (`user_id`);--> statement-breakpoint
CREATE INDEX `user_invoicing_details_user_idx` ON `user_invoicing_detail` (`user_id`);