PRAGMA foreign_keys=OFF;--> statement-breakpoint
CREATE TABLE `__new_contact` (
	`id` text PRIMARY KEY NOT NULL,
	`user_id` text NOT NULL,
	`name` text NOT NULL,
	`street` text,
	`street2` text,
	`city` text,
	`zip` text,
	`country` text,
	`registration_no` text,
	`main_email` text,
	`vat_no` text,
	`phone_number` text,
	`created_at` text DEFAULT CURRENT_TIMESTAMP NOT NULL,
	`updated_at` text
);
--> statement-breakpoint
INSERT INTO `__new_contact`("id", "user_id", "name", "street", "street2", "city", "zip", "country", "registration_no", "main_email", "vat_no", "phone_number", "created_at", "updated_at") SELECT "id", "user_id", "name", "street", "street2", "city", "zip", "country", "registration_no", "main_email", "vat_no", "phone_number", "created_at", "updated_at" FROM `contact`;--> statement-breakpoint
DROP TABLE `contact`;--> statement-breakpoint
ALTER TABLE `__new_contact` RENAME TO `contact`;--> statement-breakpoint
PRAGMA foreign_keys=ON;--> statement-breakpoint
CREATE INDEX `contact_user_idx` ON `contact` (`user_id`);--> statement-breakpoint
CREATE UNIQUE INDEX `contact_user_id_name_unique` ON `contact` (`user_id`,`name`);--> statement-breakpoint
CREATE TABLE `__new_invoice` (
	`id` text PRIMARY KEY NOT NULL,
	`user_id` text NOT NULL,
	`proforma` integer,
	`partial_proforma` integer,
	`number` text NOT NULL,
	`variable_symbol` text,
	`your_name` text,
	`your_street` text,
	`your_street2` text,
	`your_city` text,
	`your_zip` text,
	`your_country` text,
	`your_registration_no` text,
	`your_vat_no` text,
	`client_name` text,
	`client_street` text,
	`client_street2` text,
	`client_city` text,
	`client_zip` text,
	`client_country` text,
	`client_registration_no` text,
	`client_vat_no` text,
	`subject_id` integer,
	`generator_id` integer,
	`related_id` integer,
	`token` text,
	`status` text,
	`order_number` text,
	`issued_on` text,
	`taxable_fulfillment_due` text,
	`due_in_days` integer NOT NULL,
	`due_on` text NOT NULL,
	`sent_at` text,
	`paid_on` text,
	`reminder_sent_at` text,
	`cancelled_at` text,
	`bank_account` text,
	`iban` text,
	`swift_bic` text,
	`payment_method` text,
	`currency` text NOT NULL,
	`exchange_rate` real,
	`language` text,
	`transferred_tax_liability` integer,
	`supply_code` text,
	`subtotal` real,
	`total` real NOT NULL,
	`native_subtotal` real NOT NULL,
	`native_total` real,
	`remaining_amount` real,
	`remaining_native_amount` real,
	`paid_amount` real DEFAULT 0 NOT NULL,
	`note` text,
	`footer_note` text,
	`tags` text,
	`vat_base_21` real,
	`vat_21` real,
	`vat_base_15` real,
	`vat_15` real,
	`vat_base_12` real,
	`vat_12` real,
	`vat_base_10` real,
	`vat_10` real,
	`vat_base_0` real,
	`private_note` text,
	`correction` integer,
	`correction_id` integer,
	`client_email` text,
	`client_phone` text,
	`custom_id` text,
	`oss` integer,
	`tax_document` integer,
	`payment_method_human` text,
	`created_at` text DEFAULT CURRENT_TIMESTAMP NOT NULL,
	`updated_at` text,
	`published_at` text,
	`client_contact_id` text NOT NULL,
	FOREIGN KEY (`client_contact_id`) REFERENCES `contact`(`id`) ON UPDATE no action ON DELETE no action
);
--> statement-breakpoint
INSERT INTO `__new_invoice`("id", "user_id", "proforma", "partial_proforma", "number", "variable_symbol", "your_name", "your_street", "your_street2", "your_city", "your_zip", "your_country", "your_registration_no", "your_vat_no", "client_name", "client_street", "client_street2", "client_city", "client_zip", "client_country", "client_registration_no", "client_vat_no", "subject_id", "generator_id", "related_id", "token", "status", "order_number", "issued_on", "taxable_fulfillment_due", "due_in_days", "due_on", "sent_at", "paid_on", "reminder_sent_at", "cancelled_at", "bank_account", "iban", "swift_bic", "payment_method", "currency", "exchange_rate", "language", "transferred_tax_liability", "supply_code", "subtotal", "total", "native_subtotal", "native_total", "remaining_amount", "remaining_native_amount", "paid_amount", "note", "footer_note", "tags", "vat_base_21", "vat_21", "vat_base_15", "vat_15", "vat_base_12", "vat_12", "vat_base_10", "vat_10", "vat_base_0", "private_note", "correction", "correction_id", "client_email", "client_phone", "custom_id", "oss", "tax_document", "payment_method_human", "created_at", "updated_at", "published_at", "client_contact_id") SELECT "id", "user_id", "proforma", "partial_proforma", "number", "variable_symbol", "your_name", "your_street", "your_street2", "your_city", "your_zip", "your_country", "your_registration_no", "your_vat_no", "client_name", "client_street", "client_street2", "client_city", "client_zip", "client_country", "client_registration_no", "client_vat_no", "subject_id", "generator_id", "related_id", "token", "status", "order_number", "issued_on", "taxable_fulfillment_due", "due_in_days", "due_on", "sent_at", "paid_on", "reminder_sent_at", "cancelled_at", "bank_account", "iban", "swift_bic", "payment_method", "currency", "exchange_rate", "language", "transferred_tax_liability", "supply_code", "subtotal", "total", "native_subtotal", "native_total", "remaining_amount", "remaining_native_amount", "paid_amount", "note", "footer_note", "tags", "vat_base_21", "vat_21", "vat_base_15", "vat_15", "vat_base_12", "vat_12", "vat_base_10", "vat_10", "vat_base_0", "private_note", "correction", "correction_id", "client_email", "client_phone", "custom_id", "oss", "tax_document", "payment_method_human", "created_at", "updated_at", "published_at", "client_contact_id" FROM `invoice`;--> statement-breakpoint
DROP TABLE `invoice`;--> statement-breakpoint
ALTER TABLE `__new_invoice` RENAME TO `invoice`;--> statement-breakpoint
CREATE INDEX `invoices_user_idx` ON `invoice` (`user_id`);--> statement-breakpoint
CREATE UNIQUE INDEX `invoice_user_id_number_unique` ON `invoice` (`user_id`,`number`);