ALTER TABLE `contact` RENAME COLUMN "due" TO "default_invoice_due_in_days";--> statement-breakpoint
CREATE TABLE `received_invoice` (
	`id` text PRIMARY KEY NOT NULL,
	`user_id` text NOT NULL,
	`supplier_contact_id` text,
	`supplier_name` text NOT NULL,
	`supplier_street` text,
	`supplier_street2` text,
	`supplier_city` text,
	`supplier_zip` text,
	`supplier_country` text,
	`supplier_registration_no` text,
	`supplier_vat_no` text,
	`supplier_email` text,
	`supplier_phone` text,
	`invoice_number` text NOT NULL,
	`internal_number` text,
	`variable_symbol` text,
	`expense_category` text,
	`issue_date` text NOT NULL,
	`taxable_supply_date` text,
	`due_date` text NOT NULL,
	`receipt_date` text,
	`payment_date` text,
	`total_without_vat` real,
	`total_with_vat` real NOT NULL,
	`currency` text DEFAULT 'CZK' NOT NULL,
	`exchange_rate` real,
	`vat_base_21` real,
	`vat_21` real,
	`vat_base_15` real,
	`vat_15` real,
	`vat_base_10` real,
	`vat_10` real,
	`vat_base_0` real,
	`reverse_charge` integer,
	`vat_regime` text,
	`payment_method` text,
	`bank_account` text,
	`iban` text,
	`swift_bic` text,
	`items` text,
	`status` text DEFAULT 'received' NOT NULL,
	`attachment_path` text,
	`notes` text,
	`tags` text,
	`created_at` text DEFAULT CURRENT_TIMESTAMP NOT NULL,
	`updated_at` text,
	`accounting_period` text,
	FOREIGN KEY (`supplier_contact_id`) REFERENCES `contact`(`id`) ON UPDATE no action ON DELETE no action
);
--> statement-breakpoint
CREATE INDEX `received_invoices_user_idx` ON `received_invoice` (`user_id`);--> statement-breakpoint
CREATE INDEX `received_invoices_supplier_contact_id_idx` ON `received_invoice` (`supplier_contact_id`);--> statement-breakpoint
CREATE UNIQUE INDEX `received_invoice_user_id_supplier_name_invoice_number_unique` ON `received_invoice` (`user_id`,`supplier_name`,`invoice_number`);--> statement-breakpoint
ALTER TABLE `contact` ADD `default_invoice_item_unit` text;